### PR TITLE
Vendor

### LINKED ISSUE #16: use kops as go library

### PR DESCRIPTION
**Pull request by drewwells**
To make this work you must go to the vendored kops1.18.0-alpha2 directory and run `make upup/models/bindata.go`. If that doesn't work, you can run the make on your own copy of the directory and copy the upup/models/bindata.go file to the same location in your vendored directory

### CODE REVIEW

**Comment by hryan-ib** [comment]
Shaun noted an issue that is out of our hands at the moment. In the 1.18 alpha version of Kops, it allows you to specify a file to use as the kubeconfig when calling `kops validate`. This code is no working properly just yet, as it is calling other kops functions but only passing the default kubeconfig file, not the one specified. Hopefully this is resolved by them soon. I will try and find a work around for now.

**Comment by hryan-ib** [comment]
Example output   
On startup:   
```
[hryan@tac-ml-hryan cluster-operator (vendor ✗)]$ make deploy-local
operator-sdk generate k8s # codegen
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [clusteroperator:[v1alpha1], ] 
INFO[0012] Code-generation complete.                    
kubectl apply -f deploy/cluster-operator/crds/cluster-operator.infobloxopen.github.com_clusters_crd.yaml
customresourcedefinition.apiextensions.k8s.io/clusters.cluster-operator.infobloxopen.github.com unchanged
# TODO: move operator-sdk into chart
OPERATOR_NAME=clusterop .bin/operator-sdk-v0.15.2 run --local --namespace `cat .id` --operator-flags='--zap-devel'
INFO[0000] Running the operator locally in namespace hryan. 
2020-04-01T14:08:27.045-0700    INFO    cmd     Operator Version: 0.0.1
2020-04-01T14:08:27.045-0700    INFO    cmd     Go Version: go1.14
2020-04-01T14:08:27.045-0700    INFO    cmd     Go OS/Arch: darwin/amd64
2020-04-01T14:08:27.045-0700    INFO    cmd     Version of operator-sdk: v0.15.2
2020-04-01T14:08:27.046-0700    INFO    leader  Trying to become the leader.
2020-04-01T14:08:27.046-0700    INFO    leader  Skipping leader election; not running in a cluster.
2020-04-01T14:08:27.355-0700    INFO    controller-runtime.metrics      metrics server is starting to listen      {"addr": "0.0.0.0:8383"}
2020-04-01T14:08:27.355-0700    INFO    cmd     Registering Components.
2020-04-01T14:08:27.355-0700    INFO    cmd     Skipping CR metrics server creation; not running in a cluster.
2020-04-01T14:08:27.355-0700    INFO    cmd     Starting the Cmd.
2020-04-01T14:08:27.355-0700    INFO    controller-runtime.manager      starting metrics server   {"path": "/metrics"}
2020-04-01T14:08:27.355-0700    INFO    controller-runtime.controller   Starting EventSource      {"controller": "cluster-controller", "source": "kind source: /, Kind="}
2020-04-01T14:08:27.460-0700    INFO    controller-runtime.controller   Starting EventSource      {"controller": "cluster-controller", "source": "kind source: /, Kind="}
2020-04-01T14:08:27.561-0700    INFO    controller-runtime.controller   Starting Controller       {"controller": "cluster-controller"}
2020-04-01T14:08:27.561-0700    INFO    controller-runtime.controller   Starting workers {"controller": "cluster-controller", "worker count": 1}
```

On Creation:   
```
2020-04-01T14:08:53.953-0700    INFO    controller_cluster      Phase: PENDING  {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
I0401 14:08:56.007271   19634 replace_cluster.go:156] instanceGroup: master-us-east-2a was not found, creating resource now
I0401 14:08:56.500802   19634 replace_cluster.go:156] instanceGroup: nodes was not found, creating resource now
2020-04-01T14:08:56.973-0700    INFO    controller_cluster      Cluster Created {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T14:08:56.986-0700    DEBUG   controller-runtime.controller   Successfully Reconciled   {"controller": "cluster-controller", "request": "hryan/example-cluster"}
2020-04-01T14:08:56.987-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
```

On Update (cloudonly kops-rolling):   
Issues: existing error spouts at the end, need to find root cause. Also seems to enter the update loop twice, need to find whats doing that.
```
2020-04-01T14:08:57.003-0700    INFO    controller_cluster      Phase: UPDATE   {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
I0401 14:09:01.281809   19634 executor.go:103] Tasks: 0 done / 84 total; 41 can run
I0401 14:09:02.674288   19634 vfs_castore.go:675] Issuing new certificate: "apiserver-aggregator-ca"
I0401 14:09:02.683077   19634 vfs_castore.go:675] Issuing new certificate: "ca"
I0401 14:09:02.749919   19634 vfs_castore.go:675] Issuing new certificate: "etcd-manager-ca-main"
I0401 14:09:02.854030   19634 vfs_castore.go:675] Issuing new certificate: "etcd-clients-ca"
I0401 14:09:02.906900   19634 vfs_castore.go:675] Issuing new certificate: "etcd-peers-ca-events"
I0401 14:09:03.091333   19634 vfs_castore.go:675] Issuing new certificate: "etcd-manager-ca-events"
I0401 14:09:03.220656   19634 vfs_castore.go:675] Issuing new certificate: "etcd-peers-ca-main"
I0401 14:09:04.438762   19634 executor.go:103] Tasks: 41 done / 84 total; 24 can run
I0401 14:09:05.678406   19634 vfs_castore.go:675] Issuing new certificate: "kubelet"
I0401 14:09:05.856576   19634 vfs_castore.go:675] Issuing new certificate: "kubelet-api"
I0401 14:09:05.900970   19634 vfs_castore.go:675] Issuing new certificate: "kube-controller-manager"
I0401 14:09:05.978390   19634 vfs_castore.go:675] Issuing new certificate: "kubecfg"
I0401 14:09:06.049331   19634 vfs_castore.go:675] Issuing new certificate: "kube-scheduler"
I0401 14:09:06.052606   19634 vfs_castore.go:675] Issuing new certificate: "apiserver-aggregator"
I0401 14:09:06.079820   19634 vfs_castore.go:675] Issuing new certificate: "kops"
I0401 14:09:06.121936   19634 vfs_castore.go:675] Issuing new certificate: "apiserver-proxy-client"
I0401 14:09:06.163515   19634 vfs_castore.go:675] Issuing new certificate: "master"
I0401 14:09:06.399151   19634 vfs_castore.go:675] Issuing new certificate: "kube-proxy"
I0401 14:09:07.716094   19634 executor.go:103] Tasks: 65 done / 84 total; 17 can run
I0401 14:09:09.114864   19634 launchconfiguration.go:375] waiting for IAM instance profile "nodes.hryan.soheil.belamaric.com" to be ready
I0401 14:09:09.173989   19634 launchconfiguration.go:375] waiting for IAM instance profile "masters.hryan.soheil.belamaric.com" to be ready
I0401 14:09:20.790830   19634 executor.go:103] Tasks: 82 done / 84 total; 2 can run
I0401 14:09:21.593571   19634 executor.go:103] Tasks: 84 done / 84 total; 0 can run
I0401 14:09:21.593635   19634 dns.go:155] Pre-creating DNS records

Cluster changes have been applied to the cloud.


Changes may require instances to restart: kops rolling-update cluster

kops has set your kubectl context to hryan.soheil.belamaric.com
2020-04-01T14:09:24.058-0700    INFO    controller_cluster      KUBECONFIG Updated      {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
NAME                    STATUS  NEEDUPDATE      READY   MIN     MAX
master-us-east-2a       Ready   0               0       1       1
nodes                   Ready   0               0       2       2

No rolling-update required.
2020-04-01T14:09:25.050-0700    INFO    controller_cluster      Cluster Updated {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T14:09:25.077-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T14:09:25.091-0700    INFO    controller_cluster      Phase: UPDATE   {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
I0401 14:09:29.167743   19634 executor.go:103] Tasks: 0 done / 84 total; 41 can run
I0401 14:09:29.972471   19634 executor.go:103] Tasks: 41 done / 84 total; 24 can run
I0401 14:09:30.628453   19634 executor.go:103] Tasks: 65 done / 84 total; 17 can run
I0401 14:09:32.216196   19634 executor.go:103] Tasks: 82 done / 84 total; 2 can run
I0401 14:09:32.404334   19634 executor.go:103] Tasks: 84 done / 84 total; 0 can run
I0401 14:09:32.404376   19634 dns.go:155] Pre-creating DNS records

Cluster changes have been applied to the cloud.


Changes may require instances to restart: kops rolling-update cluster

kops has set your kubectl context to hryan.soheil.belamaric.com
2020-04-01T14:09:33.879-0700    INFO    controller_cluster      KUBECONFIG Updated      {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
NAME                    STATUS  NEEDUPDATE      READY   MIN     MAX
master-us-east-2a       Ready   0               1       1       1
nodes                   Ready   0               2       2       2

No rolling-update required.
2020-04-01T14:09:34.882-0700    INFO    controller_cluster      Cluster Updated {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T14:09:34.896-0700    ERROR   controller-runtime.controller   Reconciler error {"controller": "cluster-controller", "request": "hryan/example-cluster", "error": "Operation cannot be fulfilled on clusters.cluster-operator.infobloxopen.github.com \"example-cluster\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
        /Users/hryan/go/src/cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```   

On Validate:   
It will give an error on the validate until the cluster is fully ready. We may want to make that a bit more graceful.   
```
2020-04-01T14:09:35.915-0700    INFO    controller_cluster      Phase: SETUP    {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
Validating cluster hryan.soheil.belamaric.com

2020-04-01T14:09:36.558-0700    ERROR   controller-runtime.controller   Reconciler error {"controller": "cluster-controller", "request": "hryan/example-cluster", "error": "unexpected error during validation: unable to resolve Kubernetes cluster API URL dns: lookup api.hryan.soheil.belamaric.com: no such host"}
github.com/go-logr/zapr.(*zapLogger).Error
        /Users/hryan/go/src/cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88   
`2020-04-01T16:44:35.700-0700    INFO    controller_cluster      Phase: SETUP    {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
Validating cluster hryan.soheil.belamaric.com

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-2a       Master  t2.micro        1       1       us-east-2a
nodes                   Node    t2.micro        2       2       us-east-2a,us-east-2b

NODE STATUS
NAME                                            ROLE    READY
ip-172-17-17-169.us-east-2.compute.internal     master  True
ip-172-17-17-76.us-east-2.compute.internal      node    True
ip-172-17-18-131.us-east-2.compute.internal     node    True

Your cluster hryan.soheil.belamaric.com is ready
2020-04-01T16:44:38.037-0700    INFO    controller_cluster      Cluster Created {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T16:44:38.058-0700    DEBUG   controller-runtime.controller   Successfully Reconciled   {"controller": "cluster-controller", "request": "hryan/example-cluster"}
```

On Done:   
```
2020-04-01T16:44:38.058-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T16:44:38.071-0700    INFO    controller_cluster      Phase: DONE     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T16:44:38.071-0700    DEBUG   controller-runtime.controller   Successfully Reconciled   {"controller": "cluster-controller", "request": "hryan/example-cluster"}
```

On Deletion:    
The error after deletion is fixed in another PR   
```
2020-04-01T16:46:43.655-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
TYPE                    NAME                                                             ID
autoscaling-config      master-us-east-2a.masters.hryan.soheil.belamaric.com-20200401230152                       master-us-east-2a.masters.hryan.soheil.belamaric.com-20200401230152
autoscaling-config      nodes.hryan.soheil.belamaric.com-20200401230152                  nodes.hryan.soheil.belamaric.com-20200401230152
autoscaling-group       master-us-east-2a.masters.hryan.soheil.belamaric.com             master-us-east-2a.masters.hryan.soheil.belamaric.com
autoscaling-group       nodes.hryan.soheil.belamaric.com                                 nodes.hryan.soheil.belamaric.com
iam-instance-profile    masters.hryan.soheil.belamaric.com                               masters.hryan.soheil.belamaric.com
iam-instance-profile    nodes.hryan.soheil.belamaric.com                                 nodes.hryan.soheil.belamaric.com
iam-role                masters.hryan.soheil.belamaric.com                               masters.hryan.soheil.belamaric.com
iam-role                nodes.hryan.soheil.belamaric.com                                 nodes.hryan.soheil.belamaric.com
instance                master-us-east-2a.masters.hryan.soheil.belamaric.com             i-0c4ad373cef992cbf
instance                nodes.hryan.soheil.belamaric.com                                 i-0c36d4d05f508d0d2
instance                nodes.hryan.soheil.belamaric.com                                 i-0f5fad19c19de8096
keypair                 kubernetes.hryan.soheil.belamaric.com-10:75:db:0f:5a:10:c9:ea:60:39:4a:e5:1a:ea:57:36     kubernetes.hryan.soheil.belamaric.com-10:75:db:0f:5a:10:c9:ea:60:39:4a:e5:1a:ea:57:36
route-table             hryan.soheil.belamaric.com                                       rtb-0d0f4de206f3cb6ac
route53-record          api.hryan.soheil.belamaric.com.                                  Z3AGHV47UW7KPM/api.hryan.soheil.belamaric.com.
route53-record          api.internal.hryan.soheil.belamaric.com.                         Z3AGHV47UW7KPM/api.internal.hryan.soheil.belamaric.com.
security-group          masters.hryan.soheil.belamaric.com                               sg-08108a7e82861cdd3
security-group          nodes.hryan.soheil.belamaric.com                                 sg-0f59707b635be6666
subnet                  us-east-2a.hryan.soheil.belamaric.com                            subnet-014ff17d073824b31
subnet                  us-east-2b.hryan.soheil.belamaric.com                            subnet-0fb8b56a607038cc4
volume                  a.etcd-events.hryan.soheil.belamaric.com                         vol-05ca04044457324c5
volume                  a.etcd-main.hryan.soheil.belamaric.com                           vol-0be43d380221f0f6a

keypair:kubernetes.hryan.soheil.belamaric.com-10:75:db:0f:5a:10:c9:ea:60:39:4a:e5:1a:ea:57:36     ok
route53-record:Z3AGHV47UW7KPM/api.hryan.soheil.belamaric.com.   ok
autoscaling-group:master-us-east-2a.masters.hryan.soheil.belamaric.com  ok
instance:i-0f5fad19c19de8096    ok
iam-instance-profile:masters.hryan.soheil.belamaric.com ok
instance:i-0c4ad373cef992cbf    ok
instance:i-0c36d4d05f508d0d2    ok
iam-instance-profile:nodes.hryan.soheil.belamaric.com   ok
autoscaling-group:nodes.hryan.soheil.belamaric.com      ok
iam-role:masters.hryan.soheil.belamaric.com     ok
iam-role:nodes.hryan.soheil.belamaric.com       ok
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
volume:vol-0be43d380221f0f6a    still has dependencies, will retry
autoscaling-config:nodes.hryan.soheil.belamaric.com-20200401230152      ok
autoscaling-config:master-us-east-2a.masters.hryan.soheil.belamaric.com-20200401230152  ok
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
volume:vol-05ca04044457324c5    still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
security-group:sg-08108a7e82861cdd3     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        security-group:sg-08108a7e82861cdd3
        volume:vol-0be43d380221f0f6a
        subnet:subnet-014ff17d073824b31
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        volume:vol-05ca04044457324c5
        subnet:subnet-0fb8b56a607038cc4
volume:vol-0be43d380221f0f6a    still has dependencies, will retry
volume:vol-05ca04044457324c5    still has dependencies, will retry
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
security-group:sg-08108a7e82861cdd3     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        volume:vol-0be43d380221f0f6a
        subnet:subnet-014ff17d073824b31
        security-group:sg-08108a7e82861cdd3
        volume:vol-05ca04044457324c5
        subnet:subnet-0fb8b56a607038cc4
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
volume:vol-0be43d380221f0f6a    still has dependencies, will retry
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
volume:vol-05ca04044457324c5    still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
security-group:sg-08108a7e82861cdd3     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        volume:vol-0be43d380221f0f6a
        subnet:subnet-014ff17d073824b31
        security-group:sg-08108a7e82861cdd3
        volume:vol-05ca04044457324c5
        subnet:subnet-0fb8b56a607038cc4
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
volume:vol-05ca04044457324c5    still has dependencies, will retry
volume:vol-0be43d380221f0f6a    still has dependencies, will retry
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
security-group:sg-08108a7e82861cdd3     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        subnet:subnet-014ff17d073824b31
        security-group:sg-08108a7e82861cdd3
        volume:vol-0be43d380221f0f6a
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        volume:vol-05ca04044457324c5
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
volume:vol-05ca04044457324c5    ok
volume:vol-0be43d380221f0f6a    ok
security-group:sg-0f59707b635be6666     still has dependencies, will retry
security-group:sg-08108a7e82861cdd3     ok
Not all resources deleted; waiting before reattempting deletion
        subnet:subnet-014ff17d073824b31
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        subnet:subnet-014ff17d073824b31
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
        security-group:sg-0f59707b635be6666
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        subnet:subnet-014ff17d073824b31
        subnet:subnet-0fb8b56a607038cc4
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
subnet:subnet-014ff17d073824b31 still has dependencies, will retry
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        subnet:subnet-014ff17d073824b31
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
subnet:subnet-014ff17d073824b31 ok
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
        security-group:sg-0f59707b635be6666
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-0fb8b56a607038cc4 still has dependencies, will retry
security-group:sg-0f59707b635be6666     still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        security-group:sg-0f59707b635be6666
        route-table:rtb-0d0f4de206f3cb6ac
        subnet:subnet-0fb8b56a607038cc4
subnet:subnet-0fb8b56a607038cc4 ok
security-group:sg-0f59707b635be6666     ok
route-table:rtb-0d0f4de206f3cb6ac       ok
Deleted kubectl config for hryan.soheil.belamaric.com

Deleted cluster: "hryan.soheil.belamaric.com"
2020-04-01T16:49:19.368-0700    INFO    controller_cluster      Cluster Deleted {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T16:49:19.386-0700    DEBUG   controller-runtime.controller   Successfully Reconciled   {"controller": "cluster-controller", "request": "hryan/example-cluster"}
2020-04-01T16:49:19.388-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "hryan", "Request.Name": "example-cluster"}
2020-04-01T16:49:19.388-0700    ERROR   controller_cluster      error requesting instance{"Request.Namespace": "hryan", "Request.Name": "example-cluster", "error": "Cluster.cluster-operator.infobloxopen.github.com \"example-cluster\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
        /Users/hryan/go/src/cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/infobloxopen/cluster-operator/pkg/controller/cluster.(*ReconcileCluster).Reconcile
        /Users/hryan/go/src/cluster-operator/pkg/controller/cluster/cluster_controller.go:97
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /Users/hryan/go/src/cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /Users/hryan/go/src/cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
2020-04-01T16:49:19.394-0700    DEBUG   controller-runtime.controller   Successfully Reconciled   {"controller": "cluster-controller", "request": "hryan/example-cluster"}
```

**Comment by burbel** [comment]
Doing this in a bit of a reverse order, but https://github.com/infobloxopen/cluster-operator/issues/16 is being addressed by this PR, I believe.  Rather than move https://github.com/infobloxopen/cluster-operator/issues/16 into VersionOne with a reference to this PR, just hoping that committing this makes us fine.  If it doesn't please add a relevant story to VersionOne so we can track this.

**Comment by drewwells** [comment]
I think we should stick to a separate binary. It will be more flexible and doesn't require us to manage building kops

**Comment by hryan-ib** [comment]
Closing for now as we are going with the binary approach

**Pull request closed without merging**
